apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-app
  labels:
    name: person-app
    app: person-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: person-app
  template:
    metadata:
      name: person-app
      labels:
        app: person-app
        name: person-app
    spec:
      restartPolicy: Always
      containers:
      - name: keycloak
        image: jinnerbichler/keycloak-k8s:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
            protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 400m
            memory: 512Mi

---

apiVersion: v1
kind: Service
metadata:
  name: person-app
  labels:
    app: person-app
    name: person-app
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 30081
  selector:
    app: person-app
    name: person-app